website/__init__.py
# -*- coding: utf-8 -*-

import os.path
from flask import Flask, render_template
from flask_babel import Babel
from commonlib.model import analytics
from website.lib import utils
from website.lib.utils import fallback_blueprint_handler_maker
import views


app = Flask('website')
app.config.from_json(os.path.join(os.getcwd(), 'app_config.json'))

utils.init_db(app)

babel = Babel(app)

views.register_blueprints(app)

app.jinja_options['extensions'].extend(['jinja2.ext.with_', 'jinja2.ext.loopcontrols'])
app.jinja_env.globals['check_date_in_future'] = utils.check_date_in_future

app.url_build_error_handlers.append(fallback_blueprint_handler_maker(views.base_bp))


# Setup 404 error handler
@app.errorhandler(404)
def not_found(_):
    return render_template('404.html'), 404


# Setup 500 error handler
@app.errorhandler(500)
def general_error(_):
    return render_template('500.html'), 500


# Web analytics tag source injector
@app.context_processor
def analytics_proc():
    analytic_objs = analytics.AnalyticTag.objects.all()
    if analytic_objs:
        return dict(tags=map(lambda x: x.tag, analytic_objs))

if app.debug:
    print list(app.url_map.iter_rules())

    # Disable caching of HTTP responses in debug mode. It's critical for debugging frontend / js code
    @app.after_request
    def no_cache(response):
        response.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate'
        response.headers['Pragma'] = 'no-cache'
        response.headers['Expires'] = '0'
        return response

website/lib/__init__.py
# -*- coding: utf-8 -*-

website/views/__init__.py
# -*- coding: utf-8 -*-


from base import base_bp
from sitemap import sitemap_bp


def register_blueprints(app):
    app.register_blueprint(base_bp)
    app.register_blueprint(sitemap_bp, url_prefix='/iA2VMsQj46k')   # чтобы враги не догадались где sitemap.xml :)

website/views/base.py
# -*- coding: utf-8 -*-


from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, make_response, g
from commonlib.model import networks, articles
from ..lib.utils import make_response_w_zero_png
from mongoengine import MultipleObjectsReturned, DoesNotExist

base_bp = Blueprint('base', __name__)


@base_bp.route('/', methods=['GET'])
def root():
    return redirect(url_for('.nets'))


@base_bp.route('/nets', methods=['GET'])
def nets():
    g.network_objs = networks.Network.objects.all()

    date_today = datetime.date(datetime.now())
    try:
        g.head_article = articles.Article.objects(
            place=u'Вводная статья',
            date_from__lte=date_today,
            date_to__gte=date_today
        ).get()
    except (MultipleObjectsReturned, DoesNotExist):
        g.head_article = None
    return render_template('networks.html')


@base_bp.route('/net/<net_name_slugified>', methods=['GET'])
def network(net_name_slugified):
    network_obj = networks.Network.objects(name_slugified=net_name_slugified).first()
    if network_obj:
        city_ids = [x.id for x in network_obj.cities]
        ordered_city_objs = networks.City.objects(id__in=city_ids).all()
        return render_template('base_network.html', network=network_obj, city_objs=ordered_city_objs)
    else:
        return render_template('no_network.html')


@base_bp.route('/cities', methods=['GET'])
def cities():
    city_objs = networks.City.objects.all()
    return render_template('cities.html', city_objs=city_objs)


@base_bp.route('/city/<city_name_slugified>', methods=['GET'])
def city_network(city_name_slugified):
    city_obj = networks.City.objects(name_slugified=city_name_slugified).first()
    if city_obj:
        network_objs = networks.Network.objects(cities=city_obj).all()
        return render_template('cities_networks.html', city=city_obj, network_objs=network_objs)
    else:
        return render_template('no_city.html')


@base_bp.route('/cat/<net_name_slugified>/<city_name_slugified>', methods=['GET'])
def catalogue(net_name_slugified, city_name_slugified):
    network_obj = networks.Network.objects(name_slugified=net_name_slugified).first()
    city_obj = networks.City.objects(name_slugified=city_name_slugified).first()
    date_today = datetime.date(datetime.now())
    if net_name_slugified == 'magnit':
        cat = networks.MagnitNetworkAction.objects(
            network=network_obj,
            cities=city_obj,
            date_from__lte=date_today,
            date_to__gte=date_today
        ).first()
        if cat:
            return render_template('cat_magnit_city.html', cat=cat, city=city_obj, network=network_obj)
    else:
        cat = networks.NetworkAction.objects(
            network=network_obj,
            cities=city_obj,
            date_from__lte=date_today,
            date_to__gte=date_today
        ).first()
        if cat:
            return render_template('cat_network_city.html', cat=cat, city=city_obj, network=network_obj)
    return render_template('no_cat.html', network=network_obj, city=city_obj)


@base_bp.route('/cat_image/<cat_oid>/<int:page>', methods=['GET'])
def cat_image(cat_oid, page):
    cat_obj = networks.NetworkAction.objects(id=cat_oid).first()
    idx = page - 1
    try:
        image_obj = cat_obj.imageset[idx]
        image = image_obj.image.read()
        content_type = image_obj.image.content_type
        resp = make_response(image)
        resp.headers['Content-Type'] = content_type
        return resp
    except (IndexError, AttributeError):
        return make_response_w_zero_png()


@base_bp.route('/magnit_cat_image/<cat_oid>/<int:cat_number>/<int:page>', methods=['GET'])
def magnit_cat_image(cat_oid, cat_number, page):
    cat_obj = networks.MagnitNetworkAction.objects(id=cat_oid).first()
    page -= 1
    cat_number -= 1
    try:
        image_obj = cat_obj.imageset_list[cat_number].imageset[page]
        image = image_obj.image.read()
        content_type = image_obj.image.content_type
        resp = make_response(image)
        resp.headers['Content-Type'] = content_type
        return resp
    except (IndexError, AttributeError):
        return make_response_w_zero_png()


@base_bp.route('/net_image/<net_name_slugified>', methods=['GET'])
def net_image(net_name_slugified):
    net_image_obj = networks.Network.objects(name_slugified=net_name_slugified).first()
    if net_image_obj:
        image = net_image_obj.image.read()
        content_type = net_image_obj.image.content_type
        resp = make_response(image)
        resp.headers['Content-Type'] = content_type
        return resp
    else:
        return make_response_w_zero_png()

website/views/sitemap.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template, make_response, g
from commonlib.model import networks


sitemap_bp = Blueprint('sitemap', __name__)


@sitemap_bp.route('/sitemap.xml', methods=['GET'])
def sitemap():
    nets = networks.Network.objects().all()
    net_mod_dates = {}
    for net in nets:
        oldest_action = networks.NetworkAction.objects(network=net).order_by('date_from').first()
        net_mod_dates[net.name_slugified] = oldest_action.date_from

    net_actions = networks.NetworkAction.objects().all()
    cities = networks.City.objects().all()
    page = render_template('sitemap.jinja2', net_mod_dates=net_mod_dates, net_actions=net_actions, cities=cities)
    resp = make_response(page)
    resp.mimetype = 'text/xml'
    return resp

website/templates/base_network.html
{% extends 'base.html' %}
{% from 'macroses.html' import city_text %}
{% block main_row %}
  <div class="col-lg-12 col-md-12 col-sm-12">
    <div class="col-lg-8 col-md-9 col-sm-9">
      <span class="title">СКИДКИ И АКЦИИ В МАГАЗИНАХ &laquo;{{ network.name|upper }}&raquo;</span>
    </div>
    <brand itemscope itemtype="http://schema.org/Brand">
      <div class="col-lg-8 col-md-9 col-sm-9 hero-feature blog-detail">
        <meta itemprop="name" content="{{ network.name }}">
        <div class="row">
          <div class="col-lg-12 col-md-12 col-sm-12">
            <img class="img-responsive" itemprop="image" src="{{ url_for('base.net_image', net_name_slugified=network.name_slugified) }}" alt="{{ network.name }}">
          </div>
        </div>
        <div class="row" style="margin-top:30px;">
          <div class="col-lg-12 col-md-12 col-sm-12">
            {% autoescape false %}
              <p itemprop="description">{{ network.description }}</p>
            {% endautoescape %}
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-3 col-sm-3 hidden-xs">
        {# advertisement #}
      </div>
      <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
          {% for item in city_objs %}
            {{ city_text(
              item.name,
              url_for(
                'base.catalogue',
                net_name_slugified=network.name_slugified,
                city_name_slugified=item.name_slugified)
              ) }}
          {% endfor %}
        </div>
      </div>
    </brand>
  </div>
{% endblock %}
{% block breadcrumb %}
  <li><a href="{{ url_for('base.root') }}" class="fa fa-home"></a></li>
  <li><a href="{{ url_for('base.nets') }}">МАГАЗИНЫ</a></li>
  <li class="active">{{ network.name|upper }}</li>
{% endblock %}

website/templates/cat_magnit_city.html
{% extends 'base.html' %}
{% from 'macroses.html' import city_text %}

{% block head_description -%}
  {{ network.name }} в
  {%- if cat.cities[0]|length > 1 %} городах {% else %}городе {% endif -%}
  {{ cat.cities|map(attribute='name')|join(', ') }}
{%- endblock %}
{% block head_keywords -%}
  {{ network.name }}, {{ cat.cities|map(attribute='name')|join(', ') }}
{%- endblock %}
{% block head_title -%}
  {{ network.name }} в
  {%- if cat.cities[0]|length > 1 %} городах {% else %}городе {% endif -%}
  {{ cat.cities|map(attribute='name')|join(', ') }}
{%- endblock %}

{% block breadcrumb %}
  <li><a href="{{ url_for('base.root') }}" class="fa fa-home"></a></li>
  <li><a href="{{ url_for('base.network', net_name_slugified=network.name_slugified) }}">{{ network.name|upper }}</a></li>
  <li class="active">{{ city.name|upper }}</li>
{% endblock %}

{% block main_row %}
  <div class="col-lg-8 col-md-7 col-sm-12">
    <div class="col-lg-12 col-sm-12">
      <span class="compact-title">
        КАТАЛОГ АКЦИЙ &laquo;{{ network.name|upper }}&raquo; &ndash; {{ cat.cities[0].name|upper }}<br>
      </span>
      <h4 class="main-title">
        {{ cat.cities|map(attribute='name')|join(', ') }} <br>
        с {{ cat.date_from|dateformat(format='d MMMM y') }} по {{ cat.date_to|dateformat(format='d MMMM y') }}
        <span class="sub-title">
          {% if check_date_in_future(cat.date_from) %}
            (ещё не началась)
          {% else %}
            (ещё {{ cat.date_to|timedeltaformat(granularity='day') }})
          {% endif %}
        </span>
      </h4>
    </div>
  </div>
  {% set lg_md_divider = 2 %}
  {%- set xs_divider = 1 %}
  <div class="col-lg-12 col-md-12 col-sm-12">
    <div class="col-lg-12 col-md-12 col-sm-12 hero-feature blog-detail">
      <ul class="nav nav-pills" role="tablist">
        {% for image_pages in cat.imageset_list %}
          <li role="presentation" {% if loop.first %} class="active"{% endif %}><a href="#pane-{{ loop.index }}" aria-controls="pane-{{ loop.index }}" role="tab" data-toggle="tab">Каталог № {{ loop.index }}</a></li>
        {% endfor %}
      </ul>
      <div class="tab-content">
        {% for image_pages in cat.imageset_list %}
          {% set imageset_idx = loop.index %}
          <div role="tabpanel" class="tab-pane {% if loop.first %} active{% endif %}" id="pane-{{ loop.index }}">
            <!-- carousel for large, medium & small devices --> {# http://jsfiddle.net/S2rnm/795/ #}
            <div id="carousel-lg-md-{{ imageset_idx }}" class="carousel slide visible-sm visible-md visible-lg">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                {% for group in image_pages.imageset|batch(lg_md_divider) -%}
                  <li data-target="#carousel-lg-md-{{ imageset_idx }}" data-slide-to="{{ loop.index0 }}"{% if loop.index0 == 0 %} class="active"{% endif %}></li>
                {% endfor %}
              </ol>
              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                {% for group in image_pages.imageset|batch(lg_md_divider) -%}
                  {%- set group_index0 = loop.index0 -%}
                  <!-- Slide -->
                  <div class="item{% if group_index0 == 0 %} active{% endif %}">
                    <div class="row">
                      {% for item in group -%}
                        <div class="col-xs-6">
                          <img src="{{ url_for('base.magnit_cat_image', cat_oid=cat.id, cat_number = imageset_idx, page = group_index0 * lg_md_divider + loop.index) }}" alt="Страница каталога не существует"/>
                          <div class="carousel-caption">Страница {{ group_index0 * lg_md_divider + loop.index }}</div>
                        </div>
                      {%- endfor %}
                    </div>
                  </div>
                {%- endfor %}
              </div>
              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-lg-md-{{ imageset_idx }}" data-slide="prev">
                <span class="icon-prev"></span>
              </a>
              <a class="right carousel-control" href="#carousel-lg-md-{{ imageset_idx }}" data-slide="next">
                <span class="icon-next"></span>
              </a>
            </div>

            <!-- carousel for xtra-small devices -->
            <div id="carousel-xs-{{ imageset_idx }}" class="carousel slide visible-xs">
              <!-- Indicators -->
              <ol class="carousel-indicators">
                {% for group in image_pages.imageset|batch(xs_divider) -%}
                  <li data-target="#carousel-xs-{{ imageset_idx }}" data-slide-to="{{ loop.index0 }}"{% if loop.index0 == 0 %} class="active"{% endif %}></li>
                {% endfor %}
              </ol>
              <!-- Wrapper for slides -->
              <div class="carousel-inner">
                {% for group in image_pages.imageset|batch(xs_divider) -%}
                  {%- set group_index0 = loop.index0 -%}
                  <!-- Slide -->
                  <div class="item{% if group_index0 == 0 %} active{% endif %}">
                    <div class="row">
                      {% for item in group -%}
                        <div class="col-xs-12">
                          <img src="{{ url_for('base.magnit_cat_image', cat_oid=cat.id, cat_number = imageset_idx, page = group_index0 * xs_divider + loop.index) }}" alt="Страница каталога не существует"/>
                          <div class="carousel-caption">Страница {{ group_index0 * xs_divider + loop.index }}</div>
                        </div>
                      {%- endfor %}
                    </div>
                  </div>
                {%- endfor %}
              </div>
              <!-- Controls -->
              <a class="left carousel-control" href="#carousel-xs-{{ imageset_idx }}" data-slide="prev">
                <span class="icon-prev"></span>
              </a>
              <a class="right carousel-control" href="#carousel-xs-{{ imageset_idx }}" data-slide="next">
                <span class="icon-next"></span>
              </a>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <script>
    $('.carousel.slide').carousel();
  </script>
{% endblock %}

website/templates/cat_network_city.html
{% extends 'base.html' %}
{% from 'macroses.html' import city_text %}

{% block head_description -%}
  {{ network.name }} в
  {%- if cat.cities[0]|length > 1 %} городах {% else %}городе {% endif -%}
  {{ cat.cities|map(attribute='name')|join(', ') }}
{%- endblock %}
{% block head_keywords -%}
  {{ network.name }}, {{ cat.cities|map(attribute='name')|join(', ') }}
{%- endblock %}
{% block head_title -%}
  {{ network.name }} в
  {%- if cat.cities[0]|length > 1 %} городах {% else %}городе {% endif -%}
  {{ cat.cities|map(attribute='name')|join(', ') }}
{%- endblock %}

{% block breadcrumb %}
  <li><a href="{{ url_for('base.root') }}" class="fa fa-home"></a></li>
  <li><a href="{{ url_for('base.network', net_name_slugified=network.name_slugified) }}">{{ network.name|upper }}</a></li>
  <li class="active">{{ city.name|upper }}</li>
{% endblock %}

{% block main_row %}
  <div class="col-lg-8 col-md-7 col-sm-12">
    <div class="col-lg-12 col-sm-12">
      <span class="compact-title">
        КАТАЛОГ АКЦИЙ &laquo;{{ network.name|upper }}&raquo; &ndash; {{ cat.cities[0].name|upper }}<br>
      </span>
      <h4 class="main-title">
        {{ cat.cities|map(attribute='name')|join(', ') }} <br>
        с {{ cat.date_from|dateformat(format='d MMMM y') }} по {{ cat.date_to|dateformat(format='d MMMM y') }}
        <span class="sub-title">
          {% if check_date_in_future(cat.date_from) %}
            (ещё не началась)
          {% else %}
            (ещё {{ cat.date_to|timedeltaformat(granularity='day') }})
          {% endif %}
        </span>
      </h4>
    </div>
  </div>
  <div class="col-lg-12 col-md-12 col-sm-12">
    <div class="col-lg-12 col-md-12 col-sm-12 hero-feature blog-detail">
      <!-- carousel for large, medium & small devices --> {# http://jsfiddle.net/S2rnm/795/ #}
      {% set lg_md_divider = 2 %}
      <div id="carousel-lg-md" class="carousel slide visible-sm visible-md visible-lg">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          {% for group in cat.imageset|batch(lg_md_divider) -%}
            <li data-target="#carousel-lg-md" data-slide-to="{{ loop.index0 }}"{% if loop.index0 == 0 %} class="active"{% endif %}></li>
          {% endfor %}
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          {% for group in cat.imageset|batch(lg_md_divider) -%}
            {%- set group_index0 = loop.index0 -%}
            <!-- Slide -->
            <div class="item{% if group_index0 == 0 %} active{% endif %}">
              <div class="row">
                {% for item in group -%}
                  <div class="col-xs-6">
                    <img src="{{ url_for('base.cat_image', cat_oid=cat.id, page = group_index0 * lg_md_divider + loop.index) }}" alt="Страница каталога не существует"/>
                    <div class="carousel-caption">Страница {{ group_index0 * lg_md_divider + loop.index }}</div>
                  </div>
                {%- endfor %}
              </div>
            </div>
          {%- endfor %}
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-lg-md" data-slide="prev">
          <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#carousel-lg-md" data-slide="next">
          <span class="icon-next"></span>
        </a>
      </div>

      <!-- carousel for xtra-small devices -->
      {%- set xs_divider = 1 %}
      <div id="carousel-xs" class="carousel slide visible-xs">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          {% for group in cat.imageset|batch(xs_divider) -%}
            <li data-target="#carousel-xs" data-slide-to="{{ loop.index0 }}"{% if loop.index0 == 0 %} class="active"{% endif %}></li>
          {% endfor %}
        </ol>
        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          {% for group in cat.imageset|batch(xs_divider) -%}
            {%- set group_index0 = loop.index0 -%}
            <!-- Slide -->
            <div class="item{% if group_index0 == 0 %} active{% endif %}">
              <div class="row">
                {% for item in group -%}
                  <div class="col-xs-12">
                    <img src="{{ url_for('base.cat_image', cat_oid=cat.id, page = group_index0 * xs_divider + loop.index) }}" alt="Страница каталога не существует"/>
                    <div class="carousel-caption">Страница {{ group_index0 * xs_divider + loop.index }}</div>
                  </div>
                {%- endfor %}
              </div>
            </div>
          {%- endfor %}
        </div>
        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-xs" data-slide="prev">
          <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#carousel-xs" data-slide="next">
          <span class="icon-next"></span>
        </a>
      </div>


    </div>
  </div>
  <script>
    $('.carousel.slide').carousel();
  </script>
{% endblock %}

website/templates/cities.html
{% extends 'base.html' %}
{% from 'macroses.html' import city_text %}
{% set active_navbar = 'cities' %}
{% block main_row %}
  {% for item in city_objs %}
    {{ city_text(
      item.name,
      url_for('base.city_network', city_name_slugified=item.name_slugified)
    ) }}
  {% endfor %}
{% endblock %}

{% block head_description -%}
  {%- if city_objs|length > 1 %}в городах {% else %}городе {% endif -%}
  {{ city_objs|map(attribute='name')|join(', ') }}
{%- endblock %}
{% block head_keywords -%}
  {{ city_objs|map(attribute='name')|join(', ') }}
{%- endblock %}
{% block head_title -%}
  {%- if city_objs|length > 1 %}в городах {% else %}городе {% endif -%}
  {{ city_objs|map(attribute='name')|join(', ') }}
{%- endblock %}

{% block breadcrumb %}
  <li><a href="{{ url_for('base.root') }}" class="fa fa-home"></a></li>
  <li class="active">ГОРОДА</li>
{% endblock %}

website/templates/cities_networks.html
{% extends 'base.html' %}
{% from 'macroses.html' import small_network_pic_n_text %}
{% block main_row %}
  {% for item in network_objs %}
    {{ small_network_pic_n_text(
      url_for('base.net_image', net_name_slugified=item.name_slugified),
      url_for(
          'base.catalogue',
          net_name_slugified=item.name_slugified,
          city_name_slugified=city.name_slugified
      ),
      item)
    }}
  {% endfor %}
{% endblock %}

{% block head_description -%}
  {{ network_objs|map(attribute='name')|join(', ') }} в городе {{ city.name }}
{%- endblock %}
{% block head_keywords -%}
  {{ network_objs|map(attribute='name')|join(', ') }}, {{ city.name }}
{%- endblock %}
{% block head_title -%}
  {{ network_objs|map(attribute='name')|join(', ') }} в городе {{ city.name }}
{%- endblock %}


{% block breadcrumb %}
  <li><a href="{{ url_for('base.root') }}" class="fa fa-home"></a></li>
  <li><a href="{{ url_for('base.cities') }}">ГОРОДА</a></li>
  <li class="active">{{ city.name|upper }}</li>
{% endblock %}

website/templates/macroses.html
{% macro small_network_pic_n_text(picture_url, link_url, network) -%}
  <div class="col-lg-4 col-sm-4 hero-feature text-center">
    <div class="thumbnail">
      <a href="{{ link_url }}" class="link-netlogo">
         <img src="{{ picture_url }}" alt="{{ network.name }}" style="width: auto; max-width: 100%;">
      </a>
      <div class="caption prod-caption">
        {% autoescape false %}
          <h4><a href="{{ link_url }}">{{ network.name }}</a></h4>
          {% if network.description %}<a href="{{ link_url }}" class="link-paragraph"><p>{{ network.description|truncate(200, False) }}</p></a>{% endif %}
        {% endautoescape %}
      </div>
    </div>
  </div>
{%- endmacro %}

{% macro city_text(city_name, link) -%}
  <div class="col-lg-4 col-md-4 col-sm-4 hero-feature text-center" itemscope itemtype="http://schema.org/Place">
    <div class="thumbnail">
      <h3 style="margin-top: 10px"><a href="{{ link }}" style="text-decoration: none"><p itemprop="name">{{ city_name }}</p></a></h3>
    </div>
  </div>
{%- endmacro %}

website/templates/navbar.html
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Навигация</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand visible-xs" href="{{ url_for('base.root') }}">Скидки! Скидки!</a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{{ url_for('base.nets') }}" {% if active_navbar == 'networks' %}class="active"{% endif %}>Магазины</a></li>
        <li><a href="{{ url_for('base.cities') }}" {% if active_navbar == 'cities' %}class="active"{% endif %}>Города</a></li>
      </ul>
    </div>
  </div>
</nav>

website/templates/no_cat.html
{% extends 'base.html' %}
{% from 'macroses.html' import city_text %}
{% block main_row %}

  <div class="col-lg-8 col-md-7 col-sm-12">
    <div class="col-lg-12 col-sm-12">
      <span class="flat-title">К сожалению, скидок сейчас нет...</span>
    </div>
  </div>
{% endblock %}

{% block breadcrumb %}
  <li><a href="{{ url_for('base.root') }}" class="fa fa-home"></a></li>
  <li><a href="{{ url_for('base.network', net_name_slugified=network.name_slugified) }}">{{ network.name|upper }}</a></li>
  <li class="active">{{ city.name|upper }}</li>
  <li class="active">...</li>
{% endblock %}

website/templates/no_city.html
{% extends 'base.html' %}
{% from 'macroses.html' import city_text %}
{% block main_row %}

  <div class="col-lg-8 col-md-7 col-sm-12">
    <div class="col-lg-12 col-sm-12">
      <span class="flat-title">Запрашиваемый вами город не найден :(</span>
    </div>
  </div>
{% endblock %}

{% block breadcrumb %}
  <li><a href="{{ url_for('base.root') }}" class="fa fa-home"></a></li>
  <li><a href="{{ url_for('base.cities') }}">ГОРОДА</a></li>
  <li class="active">...</li>
{% endblock %}

website/templates/sitemap.jinja2
<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
      {%- set earliest_action = (net_mod_dates.values()|sort)[0].strftime('%Y-%m-%d') %}
      <url>
        <loc>http://skidkaskidok.ru{{ url_for('base.nets') }}</loc>
        <lastmod>{{ earliest_action }}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>1.0</priority>
      </url>
      <url>
        <loc>http://skidkaskidok.ru{{ url_for('base.cities') }}</loc>
        <lastmod>{{ earliest_action }}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>1.0</priority>
      </url>
  {%- for city in cities %}
      <url>
        <loc>http://skidkaskidok.ru{{ url_for('base.city_network', city_name_slugified=city.name_slugified) }}</loc>
        <lastmod>{{ earliest_action }}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>1.0</priority>
      </url>
  {%- endfor %}
  {%- for net in net_mod_dates %}
      <url>
        <loc>http://skidkaskidok.ru{{ url_for('base.network', net_name_slugified=net) }}</loc>
        <lastmod>{{ net_mod_dates[net].strftime('%Y-%m-%d') }}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>1.0</priority>
      </url>
  {%- endfor %}
  {%- for action in net_actions -%}
    {% for city in action.cities %}
      <url>
        <loc>http://skidkaskidok.ru{{ url_for('base.catalogue', net_name_slugified=action.network.name_slugified, city_name_slugified=city.name_slugified) }}</loc>
        <lastmod>{{ action.date_from.strftime('%Y-%m-%d') }}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>1.0</priority>
      </url>
    {%- endfor -%}
  {%- endfor %}
</urlset>